### ISSUE TITLE
All apps crashing 

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/Timeline#37]
I probably have some dirty data. When I am not running Timeline app the following page opens and works fine :
http://127.0.0.1:8080/people/persons/{?}

but when I am running Timeline app, and open then the page again, all apps crash.

## Apps
Timeline
People
Signin
Useradmin
AdFenix

## Exception
```
"System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'AllEventsCounter' in 'MasterPage.ActionsPage'.
Version: 2.3.1.7294.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR14012.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.GetAndCacheValue(Json parent) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 47
   at Starcounter.XSON.NewtonSoftSerializer.GetValue[T](Property`1 template, Json parent, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 575
   at Starcounter.XSON.NewtonSoftSerializer.SerializeLong(Json json, Template template, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 172
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 241
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 241
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 273
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 241
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.NewtonSoftSerializer.<>c__DisplayClass10_1.<Serialize>b__0() in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 79
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, TextWriter textWriter, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 82
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 61
   at Starcounter.Internal.PuppetRestHandler.CreateJsonBodyResponse(Session session, Json root) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 229
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 231
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR14012
---> Starcounter.DbException: ScErrSchemaCodeMismatch (SCERR4177): Operation failed because input does not match schema. CLR Class is not loaded for table Simplified.Ring6.PersonEvent
Version: 2.3.1.7294.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR4177.
   at Starcounter.Binding.Bindings.CreateExceptionOnTypeDefNotFound(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Binding\Bindings.cs:line 485
   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Binding\Bindings.cs:line 353
   at Starcounter.FilterEnumerator.MoveNext() in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Mock\Enumerator.cs:line 509
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 479
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Timeline.ActionsPage.get_BindAllEventsCounter() in C:\Users\Dimitris\Documents\GitHub\Timeline\src\Timeline\ViewModels\ActionsPage.json.cs:line 43
   at lambda_method(Closure , Json )
ErrorCode=4177
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR4177
"
```

I think a try catch will fix the apps crashing atleast.
https://github.com/StarcounterApps/Timeline/blob/9b9c24587625125489520fdd121ec8dae4e68a8c/src/Timeline/ViewModels/ActionsPage.json.cs#L43

**Comment by atifwaqar** [comment]
Or maybe not, Looks like something related to `Event` changed in Simplified.

**Comment by Joltrix** [comment]
Hello! Sorry for the late response.

If you delete the database, and update Starcounter and Timeline to their latest versions, do you still get this error?

**Comment by atifwaqar** [comment]
I already have updated Starcounter and timeline. it doesnt work as expected.
But if I delete my DB and run the same setup again, things work fine, but now i dont have any data in my DB to play with Timeline project.

**Comment by Joltrix** [comment]
I suspect that the reason for the crashing had to do with the changes to Simplified that you mentioned above.

The older version of the People app created "PersonEvents" which later got deleted from the Simplified data model. Which caused the crashing.

If you now for example install the Notes app, or the People app and create some users and notes, it should fill out the Timeline (hopefully without it crashing)

**Comment by atifwaqar** [comment]
okay, but what should I do with the DBs that already have populated some data in PersonEvents?

**Comment by Joltrix** [comment]
If I'm not mistaken, I don't think it's possible to delete the PersonEvents "right away" through the administrator, due to them not "existing" in the newer versions of Starcounter, but there is a workaround that should work!

Downgrade starcounter to 2.3.1.7280 , and then delete the PersonEvents through the administrator.
so, "DELETE FROM Simplified.Ring6.PersonEvent"

That should suffice, but if it still crashes, you can delete all the events
"DELETE FROM Simplified.Ring1.Event"
"DELETE FROM Simplified.Ring1.EventInfo"
and
"DELETE FROM Simplified.Ring6.EventParticipation"

By doing so, you will still have all the "important" data, like users etc :)

**Comment by atifwaqar** [comment]
Changing SC version is an extensive job for us spanning over 2-3 hours. (Taking DB & code backups, loading Db in Ram, etc)
I don't think we can go with this solution :( 

And I have a feeling you guys have a better solution to deal with such issues.

**Comment by Joltrix** [comment]
I've talked to @ubbeK and he proposed to use the [StarDump](https://docs.starcounter.io/guides/working-with-starcounter/stardump-cli) "approach"

If your data does not contain a lot of important `Events`, then you could delete all of the events and their related tables, just to be sure some other old class does not break something with the latest version of Timeline and Starcounter. If you do however, then you could try only excluding the `Simplified.Ring6.PersonEvent`. Hopefully that should do the trick! :D

Example: `./StarDump.exe unload --file=C:\Dump\myDatabase.sqlite3 --database=Default --skiptableprefixes="Simplified.Ring6.PersonEvent Simplified.Ring1.Event Simplified.Ring1.EventInfo Simplified.Ring6.EventParticipation Simplified.Ring6.EventFilter"`


You could unload your data, and exclude all the above mentioned tables (PersonEvent,Event,EventInfo and EventParticipation), and then load your data again.

Would that be better? Or would it still take hours to complete?

**Comment by atifwaqar** [comment]
Still, it would take too much time. 

This is our DB size : 
![image](https://user-images.githubusercontent.com/4388707/31163315-269e2ee8-a8e2-11e7-91da-2a4cbeee192e.png)

**Comment by Joltrix** [comment]
Ah, I see!

Okay, I might have a better solution for this!

What about this:

You can add this in, temporarily, somewhere


```
using Simplified.Ring1;

namespace Simplified.Ring6
{
    public class PersonEvent : Event
    {
    }
}
```

and then just build, That should allow you to access the PersonEvent class and delete it from the administrator like I previously mentioned.

By doing it this way, you won't need to change your starcounter version, nor unload/load the database :)

**Comment by warpech** [comment]
Or just update `Simplified.Data.Model.dll`.

**Comment by atifwaqar** [comment]
Both solutions worked.
@warpech if my SC version is using an older version of Simplified.Data.Model.dll, but I manually update it, will it crash anything in the live environment?

**Comment by warpech** [comment]
> @warpech if my SC version is using an older version of Simplified.Data.Model.dll, but I manually update it, will it crash anything in the live environment?

Only if the newer `Simplified.Data.Model.dll` uses some API that is not available in the older Starcounter. And in that case, it would crash on startup.

*I think*...
